apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointment-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: doctorq
  source:
    repoURL: https://github.com/jumapaul/DoctorQ
    targetRevision: appointment
    path: ./AppointmentService/appointment-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: doctorq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true