services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - doctorq-net

  maildev:
    container_name: mail
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - doctorq-net

  #  elasticsearch:
  #    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
  #    container_name: elasticsearch
  #    environment:
  #      - node.name=elasticsearch
  #      - discovery.type=single-node
  #      - bootstrap.memory_lock=true
  #      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
  #    ulimits:
  #      memlock:
  #        soft: -1
  #        hard: -1
  #    volumes:
  #      - elasticsearch:/usr/share/elasticsearch/data
  #    ports:
  #      - "9200:9200"
  #    networks:
  #      - doctorq-net
  #
  #  logstash:
  #    image: docker.elastic.co/logstash/logstash:7.15.2
  #    container_name: logstash
  #    volumes:
  #      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #      - ./UserService/logs:/usr/share/logstash/user-service
  #      - ./DoctorService/logs:/usr/share/logstash/doctor-service
  #      - ./FeedbackService/logs:/usr/share/logstash/feedback-service
  #    ports:
  #      - "5044:5044"
  #    environment:
  #      - 'LS_JAVA_OPTS=-Xmx256m -Xms256m'
  #
  #    depends_on:
  #      - elasticsearch
  #    networks:
  #      - doctorq-net
  #
  #  kibana:
  #    image: docker.elastic.co/kibana/kibana:7.15.2
  #    container_name: kibana
  #    ports:
  #      - "5601:5601"
  #    environment:
  #      - ELASTICSEARCH_URL=http://elasticsearch:9200
  #      - 'NODE_OPTIONS=--max-old-space-size=2048'
  #    depends_on:
  #      - elasticsearch
  #    networks:
  #      - doctorq-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    networks:
      - doctorq-net

# Use redis free tier.
  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - doctorq-net
  #  prometheus:
  #    image: prom/prometheus
  #    container_name: prometheus
  #    restart: unless-stopped
  #    volumes:
  #      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  #    ports:
  #      - "9090:9090"
  #
  #  grafana:
  #    image: grafana/grafana
  #    container_name: grafana
  #    restart: unless-stopped
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - grafana_data:/var/lib/grafana
  #    environment:
  #      - GF_SECURITY_ADMIN_USER=admin
  #      - GF_SECURITY_ADMIN_PASSWORD=password

  #We use upstash
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    hostname: broker
    ports:
      - "9092:9092" # Maps Container Port 9092, default for Kafka client communication, to Host Port 9092
      - "9093:9093" # Maps Container Port 9093, used for advertised listeners for external clients, to Host Port 9093
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093" # Defines who can vote in the controller quorum; part of KRaft. Format nodeId@host:controllerPort
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 # PLAINTEXT is for client communication. CONTROLLER is for internal controller communication
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data  # Path where Kafka stores its logs.
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 48 #Keep logs for 2 days
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "d9FdnCKjS6yCth0ZKzZIdg"  # A unique ID for the Kafka cluster.

    volumes:
      - kafka-data:/var/lib/kafka/data  # Store Kafka logs on your local machine.
    networks:
      - doctorq-net
networks:
  doctorq-net:
    driver: bridge

volumes:
  postgres:
  elasticsearch:
  grafana_data:
  kafka-data: