#spring:
#  cloud:
#    config:
#      override-system-properties: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://44.244.227.40:8761/eureka/
#  instance:
#    prefer-ip-address: false
#    hostname: localhost
#    instance-id: ${spring.application.name}:${server.port}
#management:
#  endpoint:
#    health:
#      show-details: always
#
#  endpoints:
#    web:
#      exposure:
#        include: health
#  health:
#    circuitbreakers:
#      enabled: true

