management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      access: read_only
  info:
    env:
      enabled: true
  health:
    db:
      enabled: false
info:
  app:
    name: "DoctorQ"
    description: "An application for booking and talking to your doctor"
    version: "1.0"

