spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        event-consumer-buffer-size: 10
    instances:
      doctorCircuitBreaker:
        base-config: default

      userCircuitBreaker:
        base-config: default


server:
  port: 8030