spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            - id: authentication-service
              uri: lb:http://USER-SERVICE
              predicates:
                - Path=/api/v1/auth/**

            - id: user-service
              uri: lb:http://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - AuthenticationFilter

            - id: doctor-service
              uri: lb:http://DOCTOR-SERVICE
              predicates:
                - Path=/api/v1/doctors/**
              filters:
                - AuthenticationFilter

            - id: doctor-category-service
              uri: lb:http://DOCTOR-SERVICE
              predicates:
                - Path=/api/v1/category/**
              filters:
                - AuthenticationFilter

server:
  port: 8222

security:
  jwt:
    secret-key: e9cddb5db6c1ef9a6a5d4b4677ef1d6c6fff514fdf3fd23b9099d754b0c42b03b7560d34cd4a78620cf619e6bee5a3926b803e737153667c856081bb90d145fa