spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      globalcors:
        add-to-simple-url-handler-mapping: true
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            - id: authentication-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/userService

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - AuthenticationFilter
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/userService
            - id: favorite-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/favorite/**
              filters:
                - AuthenticationFilter
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/userService

            - id: doctor-service
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/api/v1/doctors/**
              filters:
                - AuthenticationFilter
                - name: CircuitBreaker
                  args:
                    name: doctorServiceCircuitBreaker
                    fallbackUri: forward:/fallback/doctorService

            - id: feedback-service
              uri: lb://FEEDBACK-SERVICE
              predicates:
                - Path=/api/v1/feedbacks/**
              filters:
                - AuthenticationFilter
                - name: CircuitBreaker
                  args:
                    name: feedbackServiceCircuitBreaker
                    fallbackUri: forward:/fallback/feedbackService

            - id: favorite-service
              uri: lb://FAVORITE-SERVICE
              predicates:
                - Path=/api/v1/favorite/**
              filters:
                - AuthenticationFilter
                - name: CircuitBreaker
                  args:
                    name: favoriteServiceCircuitBreaker
                    fallbackUri: forward:/fallback/favoriteService

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        event-consumer-buffer-size: 10
    instances:
      userServiceCircuitBreaker:
        base-config: default

      doctorServiceCircuitBreaker:
        base-config: default

      feedbackServiceCircuitBreaker:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 30s
    instances:
      userServiceCircuitBreaker:
        base-config: default

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 8222