spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        jdbc:
#          enabled: false
          sql: SELECT config_value FROM config WHERE serviceName=?
        native:
          search-locations: classpath:/configurations

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8000

  #    url: ${TEST_DATASOURCE_URL}    #${DATASOURCE_URL} jdbc:postgresql://doctorq.postgres.database.azure.com:5432/config
