spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        jdbc:
#          enabled: false
          sql: SELECT config_value FROM config WHERE serviceName=?
        native:
          search-locations: classpath:/configurations

  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/config
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8000