spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        jdbc:
#          enabled: false
          sql: SELECT config_value FROM config WHERE serviceName=?
        native:
          search-locations: classpath:/configurations

  datasource:
    url: jdbc:postgresql://44.244.227.40:5432/config-database
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8000



