spring:
  application:
    name: eureka-service
  config:
    import: configserver:https://config-service.jollydesert-ec6b85c2.spaincentral.azurecontainerapps.io
#    import: optional:configserver:https://config-server.jollydesert-ec6b85c2.spaincentral.azurecontainerapps.io      #${CONFIG_URL}