replicaCount: 1
image:
  repository: jumapaul/appointment-service
  pullPolicy: Always
  tag: "9883b4a"
serviceType: ClusterIP
servicePort: 80
targetPort: 8040
containerPort: 8040
probes:
  liveness:
    path: /actuator/health/liveness
    port: 8040
    initialDelaySeconds: 240
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /actuator/health/readiness
    port: 8040
    initialDelaySeconds: 240
    periodSeconds: 10
    failureThreshold: 3
configMap:
  data:
    CONFIG_URL: "http://config-service-service:80"
    FIREBASE_JSON_PATH: "/app/doctorq-crds/client_secret.json"
secretVolume:
  name: doctorq-secret-vol
  mountPath: "/app/doctorq-crds"
  secretName: user-client-secret