replicaCount: 1
image:
  repository: jumapaul/appointmet-service
  pullPolicy: Always
  tag: "374f18b"
serviceType: ClusterIP
servicePort: 80
targetPort: 8040
containerPort: 8040
probes:
  liveness:
    path: /actuator/health/liveness
    port: 8040
    initialDelaySeconds: 120
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /actuator/health/readiness
    port: 8040
    initialDelaySeconds: 120
    periodSeconds: 10
    failureThreshold: 3
configMap:
  data:
    CONFIG_URL: "http://config-service-service:80"
