replicaCount: 1
image:
  repository: jumapaul/gateway-service
  pullPolicy: IfNotPresent
  tag: "9883b4a"
serviceType: NodePort
servicePort: 80
targetPort: 8222
containerPort: 8222
probes:
  liveness:
    path: /actuator/health/liveness
    port: 8222
    initialDelaySeconds: 120
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /actuator/health/readiness
    port: 8222
    initialDelaySeconds: 120
    periodSeconds: 10
    failureThreshold: 3
configMap:
  data:
    CONFIG_URL: "http://config-service-service:80"
