apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: config-service-secret
spec:
  encryptedData:
    DB_PASSWORD: AgBQf7VES+4YrBx9I0JP5YMJi/QZu4KAngsndlARewGGWXUjymflBulzzjCdpa5221Gp/S4tzDBAegPUXvlMfmCeBlnsKKVGer/oQo4HfEpOl7yOFWlwRxD5kU2FlumyBWSFBr1b4Sw3fiKYB+OxHsvSjMqho0O4j6nPUpIaO7SrpxsX1PfWI6JUnhL32kp+Zx8iQ85OtqGNpFPlBWob9RWq53un7d3uNvB276tZgek5rwAJfB4u7Wpv33eHXkgGUXP7rr3L26aWvq0XgSO5AJIwQRTxmzNA51TkR22KwQTtmayZEDMTwdgtUF0hub1U29c+GidaeWSxXtI+19qxEmfg7w2rB3l6Q1ZgTNMhoaHEQoxBFVj/Bv7Bl23QS68JMu1MHFHRsxQknoKwfKo9YnuAH6YzUZUMlos7wtqsh/zal0qTq9WIju691PlYU2xDD0blhNUtpXoEO6LGh8HShlyXdZw0k7ELHFrNLbtzjpHj3NmUrzq4djTVUqX0GL7I3n9Aeqf6zsFrZkm2gtnXRoIAUf0MNaSUVYvcCdAG1JJHEltjebO8j3zzN02ZeoLYd0d5a7OGJOQvjA0gJ/YYGhci6fQ7fOLpT+vHp5v3FHGw6jDrR9VaA58xVFCx9Smy8YQUMVyYU8xHf2LtuFkoAOcP5VKg1PBkw+vf8O9kRa2TvItf0lyxJmCRBfXUNQ/w3WEIGT0/zJKOHg66/A==
    DB_USERNAME: AgA/5rUAGP9rrinPZmLZjYTdOz8ULR9BRQLjWXCutVTKLVj+85Owcx8JpFt/OMhbZHUCgBopY/9440gZtb6oY3f9OlwDvOer6k3dj0cePNmt/rW6A21V7BMaWch+WXpBc++ZekUALlHliqnFWVU6o3T/OduqTKrJNDmrTsWVDUjX4fofAJyN7y0OO2ypVjovRA+4f2aG6z9+/kSt1ysX5u+d2YqpRxmPrAuxiAd6doKVhfvlUsoWeHUznEGFH16kf7kMCNQyEI24Wu5AB54N601kc0QZ22mZOo0UuxhqblV7f7xvi2349YZf/DC00yak3gKs8sOmaCcZZNUvMYgJb5XyiDyib3zr0N4XHTrp+AcofUO6bBBfqlKuis/YFuKqOAscz4+Fbyf4bm46mMm1g5W2HhRDulYTgDk6glKpN41Uk3UJYgzEzSKBnoT0UE7cPZrz0CZ0Su4baBglgCp8753ohinvWTVt69L5MI5uU3hVGynWtofyIMdhCpcRNZmnPWzefoLGVl5CldWHccGLqv6/+Z6YCesclnFzXyP7klu5PXRFzJRAxwgxwUQ/agin9XrGt684upKCFB6Ou/5UD+IOB/hRn6vIHIyBySSL5QXwijq3fzbxn7GffAkIwUpcryfxk6w9F/jKmziiR84MOjyipbRY8XxG7KzTmADvtDjr1y2B90w3o4VVCm+41OLlQuhVtcqYnQo648PNT4kFUWJDXe8hOLVvE1g1UTcllw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: config-service-secret
    type: Opaque

