input{
    file{
        path => "/usr/share/logstash/user-service/user_service.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        tags => ["user-service"]
    }

    file{
        path => "/usr/share/logstash/doctor-service/doctor_service.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        tags => ["doctor-service"]
    }

     file{
        path => "/usr/share/logstash/feedback-service/feedback_service.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        tags => ["feedback-service"]
    }
}

filter{
    #add filter
}

output{
    stdout{
        codec => rubydebug
    }

    if "user-service" in [tags]{
        elasticsearch{
            hosts => ["elasticsearch:9200"]
            index => "user-logs-%{+YYYY.MM.dd}"
        }
    }

    if "doctor-service" in [tags]{
        elasticsearch{
            hosts => ["elasticsearch:9200"]
            index => "doctor-logs-%{+YYYY.MM.dd}"
        }
    }

    if "feedback-service" in [tags]{
        elasticsearch{
            hosts => ["elasticsearch:9200"]
            index => "feedback-logs-%{+YYYY.MM.dd}"
        }
    }
}