/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.doctorq.feedbackservice.kafka;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FeedbackAvcEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5292347603210856463L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FeedbackAvcEvent\",\"namespace\":\"com.doctorq.feedbackservice.kafka\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"default\":0},{\"name\":\"doctorId\",\"type\":\"long\"},{\"name\":\"rating\",\"type\":\"double\"},{\"name\":\"ratingCount\",\"type\":\"int\",\"default\":0},{\"name\":\"reviewsCount\",\"type\":\"int\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FeedbackAvcEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FeedbackAvcEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FeedbackAvcEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FeedbackAvcEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FeedbackAvcEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FeedbackAvcEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FeedbackAvcEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FeedbackAvcEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FeedbackAvcEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private long doctorId;
  private double rating;
  private int ratingCount;
  private int reviewsCount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FeedbackAvcEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param doctorId The new value for doctorId
   * @param rating The new value for rating
   * @param ratingCount The new value for ratingCount
   * @param reviewsCount The new value for reviewsCount
   */
  public FeedbackAvcEvent(java.lang.Long id, java.lang.Long doctorId, java.lang.Double rating, java.lang.Integer ratingCount, java.lang.Integer reviewsCount) {
    this.id = id;
    this.doctorId = doctorId;
    this.rating = rating;
    this.ratingCount = ratingCount;
    this.reviewsCount = reviewsCount;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return doctorId;
    case 2: return rating;
    case 3: return ratingCount;
    case 4: return reviewsCount;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: doctorId = (java.lang.Long)value$; break;
    case 2: rating = (java.lang.Double)value$; break;
    case 3: ratingCount = (java.lang.Integer)value$; break;
    case 4: reviewsCount = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'doctorId' field.
   * @return The value of the 'doctorId' field.
   */
  public long getDoctorId() {
    return doctorId;
  }


  /**
   * Sets the value of the 'doctorId' field.
   * @param value the value to set.
   */
  public void setDoctorId(long value) {
    this.doctorId = value;
  }

  /**
   * Gets the value of the 'rating' field.
   * @return The value of the 'rating' field.
   */
  public double getRating() {
    return rating;
  }


  /**
   * Sets the value of the 'rating' field.
   * @param value the value to set.
   */
  public void setRating(double value) {
    this.rating = value;
  }

  /**
   * Gets the value of the 'ratingCount' field.
   * @return The value of the 'ratingCount' field.
   */
  public int getRatingCount() {
    return ratingCount;
  }


  /**
   * Sets the value of the 'ratingCount' field.
   * @param value the value to set.
   */
  public void setRatingCount(int value) {
    this.ratingCount = value;
  }

  /**
   * Gets the value of the 'reviewsCount' field.
   * @return The value of the 'reviewsCount' field.
   */
  public int getReviewsCount() {
    return reviewsCount;
  }


  /**
   * Sets the value of the 'reviewsCount' field.
   * @param value the value to set.
   */
  public void setReviewsCount(int value) {
    this.reviewsCount = value;
  }

  /**
   * Creates a new FeedbackAvcEvent RecordBuilder.
   * @return A new FeedbackAvcEvent RecordBuilder
   */
  public static com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder newBuilder() {
    return new com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder();
  }

  /**
   * Creates a new FeedbackAvcEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FeedbackAvcEvent RecordBuilder
   */
  public static com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder newBuilder(com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder other) {
    if (other == null) {
      return new com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder();
    } else {
      return new com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder(other);
    }
  }

  /**
   * Creates a new FeedbackAvcEvent RecordBuilder by copying an existing FeedbackAvcEvent instance.
   * @param other The existing instance to copy.
   * @return A new FeedbackAvcEvent RecordBuilder
   */
  public static com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder newBuilder(com.doctorq.feedbackservice.kafka.FeedbackAvcEvent other) {
    if (other == null) {
      return new com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder();
    } else {
      return new com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for FeedbackAvcEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FeedbackAvcEvent>
    implements org.apache.avro.data.RecordBuilder<FeedbackAvcEvent> {

    private long id;
    private long doctorId;
    private double rating;
    private int ratingCount;
    private int reviewsCount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.doctorId)) {
        this.doctorId = data().deepCopy(fields()[1].schema(), other.doctorId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.rating)) {
        this.rating = data().deepCopy(fields()[2].schema(), other.rating);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ratingCount)) {
        this.ratingCount = data().deepCopy(fields()[3].schema(), other.ratingCount);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.reviewsCount)) {
        this.reviewsCount = data().deepCopy(fields()[4].schema(), other.reviewsCount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing FeedbackAvcEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.doctorq.feedbackservice.kafka.FeedbackAvcEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.doctorId)) {
        this.doctorId = data().deepCopy(fields()[1].schema(), other.doctorId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rating)) {
        this.rating = data().deepCopy(fields()[2].schema(), other.rating);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ratingCount)) {
        this.ratingCount = data().deepCopy(fields()[3].schema(), other.ratingCount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.reviewsCount)) {
        this.reviewsCount = data().deepCopy(fields()[4].schema(), other.reviewsCount);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'doctorId' field.
      * @return The value.
      */
    public long getDoctorId() {
      return doctorId;
    }


    /**
      * Sets the value of the 'doctorId' field.
      * @param value The value of 'doctorId'.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder setDoctorId(long value) {
      validate(fields()[1], value);
      this.doctorId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'doctorId' field has been set.
      * @return True if the 'doctorId' field has been set, false otherwise.
      */
    public boolean hasDoctorId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'doctorId' field.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder clearDoctorId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'rating' field.
      * @return The value.
      */
    public double getRating() {
      return rating;
    }


    /**
      * Sets the value of the 'rating' field.
      * @param value The value of 'rating'.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder setRating(double value) {
      validate(fields()[2], value);
      this.rating = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'rating' field has been set.
      * @return True if the 'rating' field has been set, false otherwise.
      */
    public boolean hasRating() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'rating' field.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder clearRating() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ratingCount' field.
      * @return The value.
      */
    public int getRatingCount() {
      return ratingCount;
    }


    /**
      * Sets the value of the 'ratingCount' field.
      * @param value The value of 'ratingCount'.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder setRatingCount(int value) {
      validate(fields()[3], value);
      this.ratingCount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ratingCount' field has been set.
      * @return True if the 'ratingCount' field has been set, false otherwise.
      */
    public boolean hasRatingCount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ratingCount' field.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder clearRatingCount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'reviewsCount' field.
      * @return The value.
      */
    public int getReviewsCount() {
      return reviewsCount;
    }


    /**
      * Sets the value of the 'reviewsCount' field.
      * @param value The value of 'reviewsCount'.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder setReviewsCount(int value) {
      validate(fields()[4], value);
      this.reviewsCount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'reviewsCount' field has been set.
      * @return True if the 'reviewsCount' field has been set, false otherwise.
      */
    public boolean hasReviewsCount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'reviewsCount' field.
      * @return This builder.
      */
    public com.doctorq.feedbackservice.kafka.FeedbackAvcEvent.Builder clearReviewsCount() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FeedbackAvcEvent build() {
      try {
        FeedbackAvcEvent record = new FeedbackAvcEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.doctorId = fieldSetFlags()[1] ? this.doctorId : (java.lang.Long) defaultValue(fields()[1]);
        record.rating = fieldSetFlags()[2] ? this.rating : (java.lang.Double) defaultValue(fields()[2]);
        record.ratingCount = fieldSetFlags()[3] ? this.ratingCount : (java.lang.Integer) defaultValue(fields()[3]);
        record.reviewsCount = fieldSetFlags()[4] ? this.reviewsCount : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FeedbackAvcEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<FeedbackAvcEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FeedbackAvcEvent>
    READER$ = (org.apache.avro.io.DatumReader<FeedbackAvcEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeLong(this.doctorId);

    out.writeDouble(this.rating);

    out.writeInt(this.ratingCount);

    out.writeInt(this.reviewsCount);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.doctorId = in.readLong();

      this.rating = in.readDouble();

      this.ratingCount = in.readInt();

      this.reviewsCount = in.readInt();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.doctorId = in.readLong();
          break;

        case 2:
          this.rating = in.readDouble();
          break;

        case 3:
          this.ratingCount = in.readInt();
          break;

        case 4:
          this.reviewsCount = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










